### ISSUE TITLE
Example on using this library

### ISSUE THREAD

**Issue by ktannady** [hardwario/arduino-DS28E17#2]
hello sir, i have bought a CJMCU-2817 module which has the DS28E17 chip.
i want to know how to use this library to pull an I2C sensor data but i couldn't find any example with this library
i hope you can help me, thankyou.

regards.

**Comment by hubmartin** [comment]
Hi, this library is obsolete and it will be removed soon. We use the source code with our Soil Sensor from which you can learn how to use the code https://github.com/hardwario/SoilSensor

**Comment by ktannady** [comment]
Thankyou for your reply sir, i will learn how to use.

regards
